" pathogen
execute pathogen#infect()
syntax on

if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" screw vi
set nocompatible

" tabs
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set encoding=utf-8

set scrolloff=3

" Store temporary files in a central spot
" The double slash at the end ensures that the filename is created with the entire path so that name collision doesn't happen
set backupdir=~/.vim-tmp/bckp//,/tmp//
set directory=~/.vim-tmp/swap//,/tmp//

set autoindent
set autoread
set showmode
set showcmd
set hidden
set history=10000
set wildmenu
set wildmode=list:longest
set visualbell
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2

" relative line numbers. Bloody awesome!
set relativenumber

set undodir=~/.vim-tmp/undo//,/tmp//
" undo-ing even after saving
set undofile

" tab completion
set wildmenu
set wildmode=list:longest,full
set ignorecase
set smartcase
" ---instead of :%s/foo/bar/g use :%s/foo/bar/---
set gdefault	
set incsearch
set showmatch
set hlsearch

" 80th column is colored to show you are going too long
set colorcolumn=80

" make the current window big, but leave others small
set winwidth=84
" We have to have a winheight bigger than we want to set winminheight. But if we set winheight to be huge before winminheight, the winminheight set will fail.
set winheight=5
set winminheight=5
set winheight=999

" .bashrc loaded on vim startup. All aliases will now work within vim
set shellcmdflag=-ic
set shell=bash

" colorscheme
set background=dark
colorscheme molokai

" Adding 6 more years to your life
nnoremap ; :
nnoremap : ;

" mapping CAPS for moving around splits instead of <C-w> ---
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" first 2 lines fixes Vim's screwed up regex search behaviour it seems
nnoremap / /\v
vnoremap / /\v

" What's this?! https://www.reddit.com/r/vim/comments/1vdrxg/space_is_a_big_key_what_do_you_map_it_to/
nmap <Space> \
nmap <Space><Space> \\

" Edit files in same directory as current file
cnoremap %% <C-R>=expand('%:h').'/'<cr>
nnoremap <leader>e :edit <C-R>=expand('%:h').'/'<cr>

" Allow saving of files as sudo when I forgot to start vim using sudo.
cnoremap w!! w !sudo tee > /dev/null %

" place the next search in the middle of the screen
nnoremap N Nzz
nnoremap n nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz
nnoremap <silent> g# g#zz

" clear the search buffer when hitting return
nnoremap <cr> :noh<cr>

" To save, 'ctrl+s' and the new favorite 'ctrl+space'
nmap <C-s> ;w<CR><CR>
" saving and then go to normal mode. This way it is easier to quit
imap <C-s> <Esc>;w<CR><CR>
"
nmap <C-Space> ;w<CR><CR>
imap <C-Space> <Esc>;w<CR><CR>

" <leader>a -> Ack Or SilverSearch or whatever
let g:ackprg = 'ag --nogroup --nocolor --column'
nnoremap <leader>a :Ag<space>
nnoremap <leader>A :Ag<space>-s<space>

" CtrlP for fuzzy file search
" <leader>f -> Search file in whole project
nnoremap <leader>f :CtrlP<cr>
" <leader>F -> Search only in the directory of the current file
nnoremap <leader>F :CtrlPCurFile<cr>
" <leader>b -> Search files that are already in the buffer
nnoremap <leader>b :CtrlPBuffer<cr>
let g:ctrlp_working_path_mode = 'ra'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " Linux/MacOSX
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set wildignore+=*/out/**
set wildignore+=*/vendor/**
let g:ctrlp_custom_ignore = {
 \ 'dir':  '\v[\/]\.(git|hg|svn)$',
 \ 'file': '\v\.(exe|so|dll)$',
 \ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
 \ }

" <leader>v -> :vs. Creates vertical split of the current buffer
nnoremap <leader>v :vs<cr>
" <leader>h -> :sp. Creates horizontal split of the current buffer
nnoremap <leader>h :sp<cr>

" <leader><leader> -> Switch between last two files
nnoremap <leader><leader> <c-^>

" <leader>w -> show directory listing
nnoremap <leader>w :e.<cr>

" <leader>x -> maximize current window
nnoremap <leader>x <C-W>_<C-W><Bar>

" <leader>l -> select all
nnoremap <leader>l ggVG

" copy paste using yankstack plugin
call yankstack#setup()
nmap Y y$
" After pasting using p or P, use these to cycle through yank history.
" Also use :Yanks to see all the yanks
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste
"
" ,c or Ctrl-c -> Copy selected text to system clipboard
vnoremap ,c "+y
vnoremap <C-c> "+y
" ,p -> Pasted from system clipboard
nnoremap ,p "+gP
" or use <C-r><C-p>+ to paste from clipboard in INSERT mode

" <leader>v -> reselect the text that was just pasted so I can perform commands (like indentation) on it
nnoremap <leader>V `[v`]


" <leader>t -> New Tab!
nnoremap <leader>t :tabnew<cr>

" <leader>B -> delete all but the open buffer
nnoremap <leader>B :e.<cr>:BufOnly<cr>
" <leader>d -> equivalent to :bd. Better than :q
nnoremap <leader>d :bd<cr>
nnoremap <leader>q :q<CR>
" commenting
nmap <leader>c \c<space>
vmap <leader>c \c<space>
" --- uncommented out elsewhere ---
" --- <leader>c<space> -> toggle comment --- use '\' as leader
" --- <leader>y -> close the current buffer without closing the window
"  (bclose.vim) ---
" --- <leader>R - rename the current file ---
" --- <leader>e -> edit files in the same directory as current directory ---
" --- <leader>b -> bring up the commant-T buffer window ---


" Search in visual mode - forwared (/) and backward(?)
function! RangeSearch(direction)
  call inputsave()
  let g:srchstr = input(a:direction)
  call inputrestore()
  if strlen(g:srchstr) > 0
    let g:srchstr = g:srchstr.
          \ '\%>'.(line("'<")-1).'l'.
          \ '\%<'.(line("'>")+1).'l'
  else
    let g:srchstr = ''
  endif
endfunction
vnoremap <silent> / :<C-U>call RangeSearch('/')<CR>:if strlen(g:srchstr) > 0\|exec '/'.g:srchstr\|endif<CR>
vnoremap <silent> ? :<C-U>call RangeSearch('?')<CR>:if strlen(g:srchstr) > 0\|exec '?'.g:srchstr\|endif<CR>



"" Custom Macros

" Tenderlove's Debug syntax
" ---<leader>D -> in normal mode puts these lines below cursor:
" puts "#" * 90 #DEBUG
" p caller #DEBUG
" puts "#" * 90 #DEBUG
nnoremap <leader>D oputs "^^ #{?# * 90}" #DEBUG<c-m>p caller.join("\n") #DEBUG<c-m>puts "$$ #{?# * 90}" #DEBUG<esc>:w<CR>
